version: '2'

services:
  web:
    image: squirrel-web-docker:3.4
    ports:
      - "3010:3010"
    links: 
      - db
    command: npm start
  db:
    image: squirrel-db-docker:0.9
    ports: 
      - "8888:8888"
    command: npm start
